Add CI support, along with some fixes for Windows.
wdas/partio pull request #83
Opened 2020-08-31 19:47 UTC by Anteru

Other changes:

* Replace `OpenGL::OpenGL` with `OpenGL::GL`, as `OpenGL::OpenGL` doesn't work on Windows.
* Use `ZLIB::ZLIB` to reference ZLIB, and add it to the public dependencies.
* Disable shared libraries by default. The library has no symbol visibility set, so on Visual C++ it will not produce a library by default as there are no symbols.

I'm not 100% certain about the `OpenGL::GL` change, and I can easily make that conditional based on Windows if that's preferred, but I don't see use of EGL either so ... it's unclear if `OpenGL::OpenGL` is really needed. For the shared library, the correct fix would be to export all symbols that could be used by clients, but I'm not sure which ones those are so I'll rather err on the side of caution here.

2020-09-11 04:40 UTC, davvid commented on .github/workflows/build.yml
> +    branches: [ master ]
`main`

2020-09-11 05:01 UTC, davvid requested changes
Thanks for the CI scripts, this is really nice.

Please address these notes and rebase.  When doing so, please also add a signed-off-by line (`git commit --amend -s` or `ctrl-i` in Git Cola) to your commit message that certifies that you wrote or otherwise have the right to pass on these changes on as an open-source patch.

Adding a signoff certifies that you adhere to https://developercertificate.org/

Thanks

2020-09-12 14:41 UTC, Anteru commented on src/tools/CMakeLists.txt
> +        OpenGL::GL
I've added a new option `PARTIO_USE_GLVND` which is `OFF` by default on Windows, and `ON` everywhere else.

2020-09-12 14:41 UTC, Anteru commented on src/lib/CMakeLists.txt
> +    target_link_libraries(partio PUBLIC ZLIB::ZLIB)
Thanks!

2020-09-12 14:41 UTC, Anteru commented on CMakeLists.txt
> +option(BUILD_SHARED_LIBS "Enabled shared libraries" OFF)
Sounds good. Done!

2020-09-12 14:41 UTC, Anteru commented on .github/workflows/build.yml
> +    branches: [ master ]
Done!

2020-09-12 14:43 UTC, Anteru commented
Thanks for the feedback. I've addressed it (hopefully all of it) and made one more small change, renaming `GTEST_ENABLED` to `PARTIO_GTEST_ENABLED` to not pollute the global namespace. Would you be ok with doing the same for `BUILD_SHARED_LIBS`? I.e. make that `PARTIO_BUILD_SHARED_LIBRARY` with the same defaults as for `PARTIO_USE_GLVND`?

2020-09-12 18:48 UTC, merged

2020-09-12 18:50 UTC, davvid commented
Thanks again, nicely done.  It looks like I introduced a typo in `CMakeLists.txt` a bit ago related to `GTEST_LOCATION` which I fixed up in b1163a9.  I did also tweak the Makefile to account for the new `PARTIO_GTEST_ENABLED`.

Regarding `BUILD_SHARED_LIBS` -- it's probably best to leave that variable as-is.  That variable is a cmake built-in, so it makes sense to continue using it for consistency/familiarity with other projects.

2020-09-12 19:09 UTC, shdwdln commented
hey Im glad I saw this!
I am building this on win64 right now and it is building partio.dll fine but it won't build partio.lib.
It is building partio.dll, partio.ilk, and partio.pdb.
Why would this be?

2020-09-12 19:19 UTC, shdwdln commented
nvm I see the problem.

2020-09-12 20:10 UTC, Anteru commented
Thanks for spotting the typo -- didn't realize I introduced it.

The reason I was suggesting to prefix it with `PARTIO_` is to make it easier to use partio as a subproject in a bigger CMake project, there I may want to use `BUILD_SHARED_LIBS` elsewhere, and unfortunately option names are global in CMake.

2020-09-12 21:14 UTC, davvid commented
That would be a nice option to add, thanks for bringing up the subproject use case.

2020-09-13 06:38 UTC, Anteru commented
I'll prepare a PR :)