Make partio publishable on PyPi
wdas/partio pull request #93
Opened 2021-07-07 15:45 UTC by alexus37

Hi,
I started this Pr since I need the python wrapper from partio in another project but don't want to put the burden of installing on the end-user. 
The idea is to build partio inside a manylinux2014 container and upload the wheel to PyPI which makes partio pip installable (pip install partio).

However, I want to mention that I am not a python packaging expert and that there probably more elegant solutions to this than what I did. I tried to achieve this without (minimal) changes to the CMake configs.

I will leave some comments in the code to explain my building workflow. 

@davvid I claimed the partio name on PyPi and added you as a maintainer so you can publish new versions

2021-07-07 15:47 UTC, alexus37 commented on CMakeLists.txt
> +# this is use for building the python wheel
The idea is to package the 
"libpartio.so.1", "partio.py",  "_partio.so", into a single wheel and therefore are unpakcing the _partio.so should look in the same directory for shared objects.

2021-07-07 15:48 UTC, alexus37 commented on Dockerfile
> +CMD (cd io && /opt/python/cp38-cp38/bin/python setup.py bdist_wheel && auditwheel repair dist/partio-1.0.0-cp38-cp38-linux_x86_64.whl)
first, we have to install the required dependencies and the call setup to build the wheel.
finally, auditwheel makes the wheel publishable to PyPi

2021-08-04 16:00 UTC, davvid requested changes
This is looking great, thanks again for making this happen. Please amend your commits with these fixups and we'll get these updates merged soon.

2021-08-05 07:52 UTC, alexus37 commented on .gitignore
> +.vscode/
pretty cool didn't know about that.

2021-08-05 08:16 UTC, alexus37 commented on setup.py
> +        build_folder = str(Path(".").absolute() / f"{self.build_temp}_{ext.name}")
replaced all the f string with the format method

2021-08-05 08:18 UTC, alexus37 commented on setup.py
> +            configure_args += []
Done, but the whole if statement is a bit pointless I kept there as a placeholder if some special configs args are required for different builds.

2021-08-05 08:28 UTC, alexus37 commented on Dockerfile
> +    /opt/python/cp39-cp39/bin/python setup.py bdist_wheel && auditwheel repair dist/partio-1.0.0-cp39-cp39-linux_x86_64.whl )
I am using this cmd to create wheels for all currently used python versions (3.6-3.9).

2021-08-05 11:56 UTC, alexus37 commented on setup.py
> +    python_requires=">=3.4",
So the earliest Python 3 version we building for is 3.6 so I replaced it with 3.6

2021-08-05 12:37 UTC, alexus37 commented on CMakeLists.txt
> +# this is use for building the python wheel
I added an option to the cmake and the setup.py

2021-08-05 12:54 UTC, alexus37 commented on CMakeLists.txt
> +set(CMAKE_INSTALL_RPATH "$ORIGIN")
I am not sure that is required in all online sources I saw they don't do it.

2021-08-05 13:00 UTC, alexus37 commented
Thanks for the detailed feedback I incorporated most of the comments.
Regarding the support of python 2.7, there are a few things that make it annoying.

First, we would need to build partio inside the manylinux1 (CentOS 5 based - EOL) docker container
which is only supported until January 2022 additionally Python 2 will reach the end of life (EOL) on January 1st, 2020.

However, I still tried to build it, but it failed, my guess is the swig version for centos is pretty old.
If you want to take a look you can just change the docker file to use quay.io/pypa/manylinux1_x86_64 as a base image
keep in mind that CMake (v2) installed on that image is too old to install partio.

2021-08-05 13:03 UTC, alexus37 commented on setup.py
> +        base_path = Path.cwd() / "build" / "install" / "lib64"
Not exactly sure what you mean, but I run get_conf_var on my machine I am getting the following output.

```python
In [1]: import sysconfig                                                                                                                                    
In [2]: sysconfig.get_config_var('LIBDIR')                                                                                                                  
Out[2]: '/home/ax/miniconda3/lib'


```

2021-08-05 13:10 UTC, alexus37 commented on setup.py
> +    version="1.0.0",
I updated the version, I can take a look at the setuptools_scm tomorrow.

2021-08-16 09:46 UTC, alexus37 commented on setup.py
> +    version="1.0.0",
I included the [setuptools_scm](https://github.com/pypa/setuptools_scm) lib and added some settings in the setup.py to determine the version number. Please verify that these are correct. To find the computed version you can run: 

```python
python setup.py --version
```

2021-09-10 19:45 UTC, davvid approved these changes

2021-09-10 21:16 UTC, merged

2021-09-10 21:18 UTC, davvid commented
Thanks again for all your help. I'll review the notes in the README.md afresh next week and attempt to do a publish into pypi. Awesome!